// This file is auto-generated by @hey-api/openapi-ts

export type APIKeyCreate = {
    /**
     * API Key名称
     */
    name: string;
    /**
     * 是否激活
     */
    is_active?: boolean;
};

export type APIKeyUpdate = {
    name?: (string | null);
    is_active?: (boolean | null);
};

/**
 * 带数据的API响应模型（支持泛型）
 */
export type APIResponseWithData = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithData_APIKeyPublic_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithData_ItemPublic_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithData_Message_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithData_TaskModel_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithData_TaskUpdateModel_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithData_Token_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithData_UserPublic_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据
     */
    data: unknown;
};

export type APIResponseWithList_APIKeyPublic_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据列表
     */
    data: Array<unknown>;
    /**
     * 数据总数
     */
    count: number;
    /**
     * 跳过的记录数
     */
    skip?: number;
    /**
     * 返回的记录数
     */
    limit?: number;
};

export type APIResponseWithList_ItemPublic_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据列表
     */
    data: Array<unknown>;
    /**
     * 数据总数
     */
    count: number;
    /**
     * 跳过的记录数
     */
    skip?: number;
    /**
     * 返回的记录数
     */
    limit?: number;
};

export type APIResponseWithList_TaskModel_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据列表
     */
    data: Array<unknown>;
    /**
     * 数据总数
     */
    count: number;
    /**
     * 跳过的记录数
     */
    skip?: number;
    /**
     * 返回的记录数
     */
    limit?: number;
};

export type APIResponseWithList_UserPublic_ = {
    /**
     * 请求是否成功
     */
    success?: boolean;
    /**
     * 错误信息（如有）
     */
    error?: (string | null);
    /**
     * 响应数据列表
     */
    data: Array<unknown>;
    /**
     * 数据总数
     */
    count: number;
    /**
     * 跳过的记录数
     */
    skip?: number;
    /**
     * 返回的记录数
     */
    limit?: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * 对话模型
 */
export type ConversationModel = {
    conversation_id: string;
    provider_id: string;
    requests: Array<RequestModel>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * 元数据模型
 */
export type MetadataModel = {
    source: string;
    client_ip: string;
    user_agent: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 请求模型
 */
export type RequestModel = {
    request_id: string;
    status: string;
    loop_type: string;
    response: string;
    feedback?: (string | null);
    responded_by: string;
    responded_at: string;
    error?: (string | null);
};

/**
 * 任务模型
 */
export type TaskModel = {
    _id?: (string | null);
    task_id: string;
    user_id?: (string | null);
    timestamp: string;
    conversations: Array<ConversationModel>;
    metadata: MetadataModel;
    created_at?: string;
    updated_at?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type EmailVerificationRequest = {
    email: string;
};

export type EmailVerificationCode = {
    email: string;
    code: string;
};

export type UserRegisterWithCode = {
    email: string;
    password: string;
    full_name?: (string | null);
    verification_code: string;
};

export type Message = {
    message: string;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AmdinTasksGetTasksData = {
    limit?: number;
    skip?: number;
    taskId?: (string | null);
    userId?: (string | null);
};

export type AmdinTasksGetTasksResponse = (APIResponseWithList_TaskModel_);

export type ApiKeysCreateApiKeyData = {
    requestBody: APIKeyCreate;
};

export type ApiKeysCreateApiKeyResponse = (APIResponseWithData_APIKeyPublic_);

export type ApiKeysGetMyApiKeysData = {
    limit?: number;
    skip?: number;
};

export type ApiKeysGetMyApiKeysResponse = (APIResponseWithList_APIKeyPublic_);

export type ApiKeysUpdateApiKeyData = {
    apiKeyId: string;
    requestBody: APIKeyUpdate;
};

export type ApiKeysUpdateApiKeyResponse = (APIResponseWithData_APIKeyPublic_);

export type ApiKeysDeleteApiKeyData = {
    apiKeyId: string;
};

export type ApiKeysDeleteApiKeyResponse = (APIResponseWithData_Message_);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (APIResponseWithList_ItemPublic_);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (APIResponseWithData_ItemPublic_);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (APIResponseWithData_ItemPublic_);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (APIResponseWithData_ItemPublic_);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (APIResponseWithData_ItemPublic_);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (APIResponseWithData_Token_);

export type LoginTestTokenResponse = (APIResponseWithData_UserPublic_);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (APIResponseWithData_Message_);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (APIResponseWithData_Message_);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (APIResponseWithData_UserPublic_);

export type TasksSyncTaskDataData = {
    requestBody: TaskModel;
    xApiKey?: (string | null);
};

export type TasksSyncTaskDataResponse = (APIResponseWithData_TaskUpdateModel_);

export type TasksGetMyTasksData = {
    limit?: number;
    skip?: number;
    taskId?: (string | null);
};

export type TasksGetMyTasksResponse = (APIResponseWithList_TaskModel_);

export type TasksGetTaskData = {
    taskId: string;
};

export type TasksGetTaskResponse = (APIResponseWithData_TaskModel_);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (APIResponseWithData);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (APIResponseWithList_UserPublic_);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (APIResponseWithData_UserPublic_);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (APIResponseWithData_Message_);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (APIResponseWithData_UserPublic_);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (APIResponseWithData_Message_);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (APIResponseWithData_UserPublic_);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (APIResponseWithData_UserPublic_);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (APIResponseWithData_UserPublic_);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (APIResponseWithData_Message_);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (APIResponseWithData_Message_);

export type UtilsHealthCheckResponse = (boolean);