"""add_humanloop_request_table

Revision ID: 91b496f2ff38
Revises: fb315ab9e446
Create Date: 2025-08-08 18:38:26.942743

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '91b496f2ff38'
down_revision = 'fb315ab9e446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('humanlooprequest',
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('loop_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('responded_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('humanlooprequest')
    # ### end Alembic commands ###
