"""Add description field to APIKey model

Revision ID: fb315ab9e446
Revises: 2ac28c0396dc
Create Date: 2025-07-30 23:18:00.743223

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fb315ab9e446'
down_revision = '2ac28c0396dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikey', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apikey', 'description')
    # ### end Alembic commands ###
